---
- name: Install Requirements
  apt: 
    name: "{{ item }}" 
    state: latest
    update_cache: yes
  loop: 
    - nginx

- name: "POC configuration"
  template:
    src: "../templates/template.j2"
    dest: "/etc/nginx/sites-available/default"
    mode: "0644"

- name: Nginx | Status
  shell: nginx -t 
  register: ngs

- debug:
    msg: "{{ ngs.stdout.split('\n') }}"

- name: Restart Nginx
  service: 
    name: nginx
    state: restarted

- name: Verify Nginx
  service: 
    name: nginx
    state: started
