---
- name: Install Nginx and create index page
  hosts: web-hy
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create index.html with greeting
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome</title>
          </head>
          <body style="font-family: sans-serif; text-align: center; margin-top: 10%;">
              <h1>Hi there!</h1>
          </body>
          </html>
